### ISSUE TITLE
Nacos 同步 到K8S 失败

### ISSUE THREAD

**Issue by im-jinxinwang** [nacos-group/nacos-controller#12]
DynamicConfiguration配置
```yaml
apiVersion: nacos.io/v1
kind: DynamicConfiguration
metadata:
    name: dc-demo-server2cluster
spec:
  dataIds:
  - test123
  nacosServer:
    endpoint: omc-nacos.omc:8848  #注明： 这个svc开放了9848
    namespace: "test123"
    group: DEFAULT_GROUP
    authRef:
      apiVersion: v1
      kind: Secret
      name: nacos-auth
  strategy:
    syncPolicy: Always
    syncDirection: server2cluster
    syncDeletion: true
---
apiVersion: v1
kind: Secret
metadata:
    name: nacos-auth
data:
    ak: bmFjb3MK
    sk: bmFjb3MK
```
报错日志：

![image](https://github.com/user-attachments/assets/bc4e2705-5543-4baa-b9bd-ebb43277795f)
nacos配置信息
![image](https://github.com/user-attachments/assets/455911d6-c1c9-4d77-a6b8-b0f7a5b0ff9c)

![image](https://github.com/user-attachments/assets/5ef1e930-57e4-4a7e-b85e-45011280d279)
