### ISSUE TITLE
请问是不是还不支持 nacos3.0

### ISSUE THREAD

**Issue by jadiy** [nacos-group/nacos-controller#26]
Nacos controller 报错如下：
```
2025-05-06T08:59:48Z	ERROR	publish Config to nacos server error	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "Secret": {"name":"paas.elb","namespace":"default"}, "namespace": "default", "name": "paas.elb", "reconcileID": "95ebd2c9-6661-458f-9870-4407676c5f16", "group": "secret.paas.elb", "dataId": "security.credential", "error": "client not connected, current status:STARTING", "errorVerbose": "client not connected, current status:STARTING\ngithub.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*RpcClient).Request\n\t/workspace/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.2.9/common/remote/rpc/rpc_client.go:591\ngithub.com/nacos-group/nacos-sdk-go/v2/clients/config_client.(*ConfigProxy).requestProxy\n\t/workspace/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.2.9/clients/config_client/config_proxy.go:59\ngithub.com/nacos-group/nacos-sdk-go/v2/clients/config_client.(*ConfigClient).PublishConfig\n\t/workspace/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.2.9/clients/config_client/config_client.go:257\ngithub.com/nacos-group/nacos-controller/pkg/nacos/client/impl.(*DefaultNacosConfigClient).PublishConfig\n\t/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/client/impl/default_client.go:143\ngithub.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).configDataIdSync\n\t/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:340\ngithub.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).configGroupSync\n\t/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:301\ngithub.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).DoReconcile\n\t/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:136\ngithub.com/nacos-group/nacos-controller/pkg/controller.(*SecretReconciler).Reconcile\n\t/workspace/src/github.com/nacos-group/nacos-controller/pkg/controller/secret_controller.go:90\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"}
github.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).configDataIdSync
	/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:355
github.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).configGroupSync
	/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:301
github.com/nacos-group/nacos-controller/pkg/nacos.(*ConfigurationSyncController).DoReconcile
	/workspace/src/github.com/nacos-group/nacos-controller/pkg/nacos/config_sync_controller.go:136
github.com/nacos-group/nacos-controller/pkg/controller.(*SecretReconciler).Reconcile
	/workspace/src/github.com/nacos-group/nacos-controller/pkg/controller/secret_controller.go:90
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
```
在 pod 里的调试记录如下：
 ```
curl -X POST 'http://nacos-0.nacos-v3.default.svc.cluster.local:8848/nacos/v3/auth/user/login' -d 'username=nacos' -d 'password=nacos'
{"accessToken":"eyJhbGxxxxOM","tokenTtl":18000,"globalAdmin":true,"username":"nacos"}
 curl -X POST 'http://nacos-0.nacos-v3.default.svc.cluster.local:8848/nacos/v3/admin/cs/config?dataId=quickstart.test.config&groupName=test&content=HelloWorld' -H "accessToken:eyJhbGxxxxOM"
{"code":0,"message":"success","data":true}
curl -X GET 'nacos-0.nacos-v3.default.svc.cluster.local:8848/nacos/v3/client/cs/config?accessToken=eyJhbGxxxxOM&dataId=quickstart.test.
config&groupName=test'
{"code":0,"message":"success","data":{"resultCode":200,"errorCode":0,"message":null,"requestId":null,"content":"HelloWorld","encryptedDataKey":"","contentType":"text","md5":"68e109f0f40ca72a15e05cc22786f8e6","lastModified":1746493980000,"tag":null,"beta":false,"success":true}}
```

以下是DynamicConfiguration的配置
```
apiVersion: nacos.io/v1
kind: DynamicConfiguration
metadata:
   name: dc-demo
   namespace: default
spec:
   nacosServer:
      # endpoint: nacos地址服务器，与serverAddr互斥，优先级高于serverAddr，与serverAddr二选一即可
      endpoint: nacos-0.nacos-v3.default.svc.cluster.local:8848
      # namespace: 用户指定的命名空间
      namespace: default
      # authRef: 引用存放Nacos 客户端鉴权信息的Secret，支持用户名/密码 和 AK/SK, Nacos服务端未开启鉴权可忽略
      authRef:
         apiVersion: v1
         kind: Secret
         name: nacos-auth
   strategy:
      # scope: 同步策略，full 表示全量同步，partial 表示部分同步
      scope: full
      # 是否同步配置删除操作
      syncDeletion: true
      # conflictPolicy: 同步冲突策略，preferCluster 表示初次同步内容冲突时以Kubernetes集群配置为准，preferServer 表示以Nacos配置为准
      conflictPolicy: preferCluster
---
apiVersion: v1
kind: Secret
metadata:
   name: nacos-auth
   namespace: default
data:
    username: bmFjb3M=
    password: bmFjb3M=
```
